export let item = [
  {
    uid: "1",
    sku: "1",
    display: true,
    name: "Bigger Satisfaction",
    price: 9.99,
    description: "Bigger Satisfaction",
    url: "https://iili.io/H1ayYla.png",
  },
  {
    uid: "2",
    sku: "2",
    display: true,
    name: "Breakfast Promo",
    price: 8.99,
    description: "Breakfast Promo",
    url: "https://iili.io/H1ay7Kg.png",
  },
  {
    uid: "3",
    sku: "3",
    display: true,
    name: "Brekkie Special",
    price: 6.99,
    description: "Brekkie Special",
    url: "https://iili.io/H1ayaUJ.png",
  },
  {
    uid: "4",
    sku: "4",
    display: true,
    name: "Chill Together",
    price: 9.99,
    description: "Chill Together",
    url: "https://iili.io/H1cFcBV.png",
  },
  {
    uid: "5",
    sku: "5",
    display: true,
    name: "Classic Favourites",
    price: 12.99,
    description: "Classic Favourites",
    url: "https://iili.io/H1ayuoP.png",
  },
  {
    uid: "6",
    sku: "6",
    display: true,
    name: "Crunchy Bites",
    price: 16.99,
    description: "Crunchy Bites",
    url: "https://iili.io/H1cF0rP.png",
  },
  {
    uid: "7",
    sku: "7",
    display: true,
    name: "Double Goodness",
    price: 9.99,
    description: "Double Goodness",
    url: "https://iili.io/H1ay0RR.png",
  },
  {
    uid: "8",
    sku: "8",
    display: true,
    name: "Monday Breakfast Special 1",
    price: 5.5,
    description: "Monday Breakfast Special 1",
    url: "https://iili.io/H1cFI29.png",
  },
  {
    uid: "9",
    sku: "9",
    display: true,
    name: "Monday Breakfast Special 2",
    price: 5.5,
    description: "Monday Breakfast Special 2",
    url: "https://iili.io/H1cFAmb.png",
  },
  {
    uid: "10",
    sku: "10",
    display: true,
    name: "Monday Breakfast Special 3",
    price: 7.5,
    description: "Monday Breakfast Special 3",
    url: "https://iili.io/H1cF7hx.png",
  },
  {
    uid: "11",
    sku: "11",
    display: true,
    name: "Monday Breakfast Special 4",
    price: 7.5,
    description: "Monday Breakfast Special 4",
    url: "https://iili.io/H1cFGYF.png",
  },
  {
    uid: "12",
    sku: "12",
    display: true,
    name: "Monday Breakfast Special 5",
    price: 6.5,
    description: "Monday Breakfast Special 5",
    url: "https://iili.io/H1cFE21.png",
  },
  {
    uid: "13",
    sku: "13",
    display: true,
    name: "Morning Surprise",
    price: 8.99,
    description: "Morning Surprise",
    url: "https://iili.io/H1ay1Np.png",
  },
  {
    uid: "14",
    sku: "14",
    display: true,
    name: "Perfect Pair",
    price: 9.99,
    description: "Perfect Pair",
    url: "https://iili.io/H1ayMxI.png",
  },
  {
    uid: "15",
    sku: "15",
    display: true,
    name: "Spicy Surprise",
    price: 9.99,
    description: "Spicy Surprise",
    url: "https://iili.io/H1cFe4I.png",
  },
  {
    uid: "16",
    sku: "16",
    display: true,
    name: "Unbeatable Duo",
    price: 10.5,
    description: "Unbeatable Duo",
    url: "https://iili.io/H1ayVVt.png",
  },
  {
    uid: "17",
    sku: "17",
    display: true,
    name: "Weekend Breakfast Special 1",
    price: 21,
    description: "Weekend Breakfast Special 1",
    url: "https://iili.io/H1cFXTJ.png",
  },
  {
    uid: "18",
    sku: "18",
    display: true,
    name: "Weekend Breakfast Special 2",
    price: 23,
    description: "Weekend Breakfast Special 2",
    url: "https://iili.io/H1cFjQR.png",
  },
];
